
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from clases.usuario import Usuario
from views import v_usuario

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Checkbutton, Button, PhotoImage, IntVar, StringVar

class Bienvenida:
    def __init__(self):
        OUTPUT_PATH = Path(__file__).parent
        ASSETS_PATH = OUTPUT_PATH / Path(r"assets_inicio\frame0")


        def relative_to_assets(path: str) -> Path:
            return ASSETS_PATH / Path(path)


        self.window = Tk()

        self.window.geometry("772x539")
        self.window.configure(bg = "#FFFFFF")

        self.usuario = StringVar()
        self.contrasenia = StringVar()

        self.nuevo_usuario = StringVar()
        self.correo = StringVar()
        self.nueva_contrasenia = StringVar()
        self.nueva_contrasenia_repeat = StringVar()
        self.direccion = StringVar()
        self.admin = IntVar()

        USUARIO = Usuario(self.usuario,
                          self.contrasenia,
                          None,
                          None,
                          0
                        )


        self.canvas = Canvas(
            self.window,
            bg = "#FFFFFF",
            height = 539,
            width = 772,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )


        self.canvas.place(x = 0, y = 0)
        self.entry_image_1 = PhotoImage(
            file=relative_to_assets("entry_1.png"))
        self.entry_bg_1 = self.canvas.create_image(
            225.0,
            55.5,
            image=self.entry_image_1
        )

        
        
        self.entry_1 = Entry(
            bd=0,
            bg="#D9D9D9",
            fg="#000716",
            highlightthickness=0,
            textvariable=self.usuario
        )

        self.entry_1.place(
            x=133.0,
            y=42.0,
            width=184.0,
            height=25.0
        )

        self.entry_image_7 = PhotoImage(
            file=relative_to_assets("entry_7.png"))
        
        self.entry_bg_7 = self.canvas.create_image(
            225.0,
            132.5,
            image=self.entry_image_7
        )

        self.entry_7 = Entry(
            bd=0,
            bg="#D9D9D9",
            fg="#000716",
            highlightthickness=0,
            textvariable=self.contrasenia
        )
        self.entry_7.place(
            x=133.0,
            y=119.0,
            width=184.0,
            height=25.0
        )

        self.button_image_1 = PhotoImage(
            file=relative_to_assets("button_1.png"))
        self.button_1 = Button(
            image=self.button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_1 clicked"),
            relief="flat"
        )
        self.button_1.place(
            x=75.0,
            y=263.0,
            width=246.0,
            height=35.0
        )

        self.button_image_2 = PhotoImage(
            file=relative_to_assets("button_2.png"))
        
        self.button_2 = Button(
            image=self.button_image_2,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print(self.admin.get(), "imprimiendo"),
            relief="flat"
        )
        self.button_2.place(
            x=478.0,
            y=412.0,
            width=246.0,
            height=35.0
        )

        ################# BOTON INGRESAR ############

        self.button_image_3 = PhotoImage(
            file=relative_to_assets("button_3.png"))
        self.ingresar = Button(
            image=self.button_image_3,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: USUARIO.comprobar_usuario(self.window, self.usuario, self.contrasenia),
            relief="flat"
        )
        self.ingresar.place(
            x=75.0,
            y=192.0,
            width=246.0,
            height=35.0
        )

        

        self.button_image_4 = PhotoImage(
            file=relative_to_assets("button_4.png"))
        self.button_4 = Button(
            image=self.button_image_4,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_4 clicked"),
            relief="flat"
        )
        self.button_4.place(
            x=26.0,
            y=340.0,
            width=319.0,
            height=25.0
        )
        ################### NUEVO REGISTRO ############################

        

        #>>>>>>>>>> NUEVO USUARIO <<<<<<<<<<<<#

        self.entry_image_2 = PhotoImage(
            file=relative_to_assets("entry_2.png"))
        self.entry_bg_2 = self.canvas.create_image(
            672.0,
            90.0,
            image=self.entry_image_2
        )
        
        
        self.entry_2 = Entry(
            bd=0,
            bg="#D9D9D9",
            fg="#000716",
            highlightthickness=0,
            textvariable=self.nuevo_usuario
        )
        self.entry_2.place(
            x=580.0,
            y=72.0,
            width=184.0,
            height=34.0
        )

        self.entry_image_3 = PhotoImage(
            file=relative_to_assets("entry_3.png"))
        self.entry_bg_3 = self.canvas.create_image(
            672.0,
            144.0,
            image=self.entry_image_3
        )
        
        #>>>>>>>>>> CORREO <<<<<<<<<<<<#

        self.entry_3 = Entry(
            bd=0,
            bg="#D9D9D9",
            fg="#000716",
            highlightthickness=0,
            textvariable=self.correo
        )
        self.entry_3.place(
            x=580.0,
            y=126.0,
            width=184.0,
            height=34.0
        )

        self.entry_image_4 = PhotoImage(
            file=relative_to_assets("entry_4.png"))
        self.entry_bg_4 = self.canvas.create_image(
            672.0,
            198.0,
            image=self.entry_image_4
        )


        self.entry_4 = Entry(
            bd=0,
            bg="#D9D9D9",
            fg="#000716",
            highlightthickness=0,
            textvariable=self.nueva_contrasenia
        )
        self.entry_4.place(
            x=580.0,
            y=180.0,
            width=184.0,
            height=34.0
        )

        self.entry_image_5 = PhotoImage(
            file=relative_to_assets("entry_5.png"))
        self.entry_bg_5 = self.canvas.create_image(
            672.0,
            252.0,
            image=self.entry_image_5
        )

        

        self.entry_5 = Entry(
            bd=0,
            bg="#D9D9D9",
            fg="#000716",
            highlightthickness=0,
            textvariable=self.nueva_contrasenia_repeat
        )
        self.entry_5.place(
            x=580.0,
            y=234.0,
            width=184.0,
            height=34.0
        )

        self.entry_image_6 = PhotoImage(
            file=relative_to_assets("entry_6.png"))
        self.entry_bg_6 = self.canvas.create_image(
            672.0,
            306.0,
            image=self.entry_image_6
        )

        
        self.entry_6 = Entry(
            bd=0,
            bg="#D9D9D9",
            fg="#000716",
            highlightthickness=0,
            textvariable=self.direccion
        )
        self.entry_6.place(
            x=580.0,
            y=288.0,
            width=184.0,
            height=34.0
        )

        self.check_1 = Checkbutton(text="SI", font=("Inter", 20 * -1), variable=self.admin)
        
        self.check_1.place(x=600.0, y=340.7)


        self.canvas.create_text(
            55.0,
            45.0,
            anchor="nw",
            text="Usuario:",
            fill="#000000",
            font=("Inter", 20 * -1)
        )

        self.canvas.create_text(
            509.0,
            132.0,
            anchor="nw",
            text="Correo:",
            fill="#000000",
            font=("Inter", 20 * -1)
        )

        self.canvas.create_text(
            484.0,
            294.0,
            anchor="nw",
            text="Dirección:",
            fill="#000000",
            font=("Inter", 20 * -1)
        )

        self.canvas.create_text(
            414.0,
            346.0,
            anchor="nw",
            text="Es administrador:",
            fill="#000000",
            font=("Inter", 20 * -1)
        )

    
        
        

        self.canvas.create_text(
            394.0,
            77.0,
            anchor="nw",
            text="Nombre de usuario:",
            fill="#000000",
            font=("Inter", 20 * -1)
        )

        self.canvas.create_text(
            394.0,
            242.0,
            anchor="nw",
            text="Repetir contraseña:",
            fill="#000000",
            font=("Inter", 20 * -1)
        )

        self.canvas.create_text(
            465.0,
            187.0,
            anchor="nw",
            text="Contraseña:",
            fill="#000000",
            font=("Inter", 20 * -1)
        )

        self.canvas.create_text(
            509.0,
            30.0,
            anchor="nw",
            text="Nuevo registro",
            fill="#000000",
            font=("Inter", 20 * -1)
        )

        self.canvas.create_text(
            18.0,
            122.0,
            anchor="nw",
            text="Contraseña:",
            fill="#000000",
            font=("Inter", 20 * -1)
        )


        self.window.resizable(False, False)
        self.window.mainloop()

    def funcion(self):
            # self.window.destroy()
            ventana = self.window
            return ventana
    # def abrir_vista(self, clase):
    #     clase = VistaUsuario()
    #     return clase