
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

class ResetPass:
    def __init__(self, window):
        window.destroy()
        OUTPUT_PATH = Path(__file__).parent
        ASSETS_PATH = OUTPUT_PATH / Path(r"assets_reset\frame0")


        def relative_to_assets(path: str) -> Path:
            return ASSETS_PATH / Path(path)


        self.window_2 = Tk()

        self.window_2.geometry("552x353")
        self.window_2.configure(bg = "#FFFFFF")


        self.canvas = Canvas(
            self.window_2,
            bg = "#FFFFFF",
            height = 353,
            width = 552,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        self.canvas.place(x = 0, y = 0)
        self.entry_image_1 = PhotoImage(
            file=relative_to_assets("entry_1.png"))
        self.entry_bg_1 = self.canvas.create_image(
            306.5,
            226.5,
            image=self.entry_image_1
        )
        self.entry_1 = Entry(
            bd=0,
            bg="#FFD2D2",
            fg="#000716",
            highlightthickness=0
        )
        self.entry_1.place(
            x=217.0,
            y=212.0,
            width=179.0,
            height=27.0
        )

        self.entry_image_2 = PhotoImage(
            file=relative_to_assets("entry_2.png"))
        self.entry_bg_2 = self.canvas.create_image(
            306.5,
            162.5,
            image=self.entry_image_2
        )
        self.entry_2 = Entry(
            bd=0,
            bg="#FFD2D2",
            fg="#000716",
            highlightthickness=0
        )
        self.entry_2.place(
            x=217.0,
            y=148.0,
            width=179.0,
            height=27.0
        )

        self.entry_image_3 = PhotoImage(
            file=relative_to_assets("entry_3.png"))
        self.entry_bg_3 = self.canvas.create_image(
            306.5,
            98.5,
            image=self.entry_image_3
        )
        self.entry_3 = Entry(
            bd=0,
            bg="#FFD2D2",
            fg="#000716",
            highlightthickness=0
        )
        self.entry_3.place(
            x=217.0,
            y=84.0,
            width=179.0,
            height=27.0
        )

        self.canvas.create_text(
            58.0,
            217.0,
            anchor="nw",
            text="Repita la contraseña:",
            fill="#000000",
            font=("Inter", 16 * -1)
        )

        self.canvas.create_text(
            75.0,
            150.0,
            anchor="nw",
            text="Nueva contraseña:",
            fill="#000000",
            font=("Inter", 16 * -1)
        )

        self.canvas.create_text(
            155.0,
            86.0,
            anchor="nw",
            text="Usuario:",
            fill="#000000",
            font=("Inter", 16 * -1)
        )

        self.canvas.create_text(
            187.0,
            24.0,
            anchor="nw",
            text="RESTABLECER CONTRASEÑA",
            fill="#000000",
            font=("Inter", 16 * -1)
        )

        self.button_image_1 = PhotoImage(
            file=relative_to_assets("button_1.png"))
        self.button_1 = Button(
            image=self.button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_1 clicked"),
            relief="flat"
        )
        self.button_1.place(
            x=217.0,
            y=279.0,
            width=176.0,
            height=38.0
        )
        self.window_2.resizable(False, False)
        self.window_2.mainloop()

if __name__ == "__main__":
    vista = ResetPass()