
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from usuario import v_usuario
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Frame

class Bienvenida:
    def __init__(self):

        OUTPUT_PATH = Path(__file__).parent
        ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame0")


        def relative_to_assets(path: str) -> Path:
            return ASSETS_PATH / Path(path)


        window = Tk()

        window.geometry("772x539")
        window.configure(bg = "#FFFFFF")



        canvas = Canvas(
            window,
            bg = "#FFFFFF",
            height = 539,
            width = 772,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )


        canvas.place(x = 0, y = 0)
        entry_image_1 = PhotoImage(
            file=relative_to_assets("entry_1.png"))
        entry_bg_1 = canvas.create_image(
            225.0,
            55.5,
            image=entry_image_1
        )
        entry_1 = Entry(
            bd=0,
            bg="#D9D9D9",
            fg="#000716",
            highlightthickness=0
        )
        entry_1.place(
            x=133.0,
            y=42.0,
            width=184.0,
            height=25.0
        )

        button_image_1 = PhotoImage(
            file=relative_to_assets("button_1.png"))
        button_1 = Button(
            image=button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_1 clicked"),
            relief="flat"
        )
        button_1.place(
            x=75.0,
            y=263.0,
            width=246.0,
            height=35.0
        )

        button_image_2 = PhotoImage(
            file=relative_to_assets("button_2.png"))
        button_2 = Button(
            image=button_image_2,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_2 clicked"),
            relief="flat"
        )
        button_2.place(
            x=478.0,
            y=412.0,
            width=246.0,
            height=35.0
        )

        button_image_3 = PhotoImage(
            file=relative_to_assets("button_3.png"))
        button_3 = Button(
            image=button_image_3,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_3 clicked"),
            relief="flat"
        )
        button_3.place(
            x=75.0,
            y=192.0,
            width=246.0,
            height=35.0
        )

        button_image_4 = PhotoImage(
            file=relative_to_assets("button_4.png"))
        button_4 = Button(
            image=button_image_4,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_4 clicked"),
            relief="flat"
        )
        button_4.place(
            x=26.0,
            y=340.0,
            width=319.0,
            height=25.0
        )

        entry_image_2 = PhotoImage(
            file=relative_to_assets("entry_2.png"))
        entry_bg_2 = canvas.create_image(
            672.0,
            90.0,
            image=entry_image_2
        )
        entry_2 = Entry(
            bd=0,
            bg="#D9D9D9",
            fg="#000716",
            highlightthickness=0
        )
        entry_2.place(
            x=580.0,
            y=72.0,
            width=184.0,
            height=34.0
        )

        entry_image_3 = PhotoImage(
            file=relative_to_assets("entry_3.png"))
        entry_bg_3 = canvas.create_image(
            672.0,
            144.0,
            image=entry_image_3
        )
        entry_3 = Entry(
            bd=0,
            bg="#D9D9D9",
            fg="#000716",
            highlightthickness=0
        )
        entry_3.place(
            x=580.0,
            y=126.0,
            width=184.0,
            height=34.0
        )

        entry_image_4 = PhotoImage(
            file=relative_to_assets("entry_4.png"))
        entry_bg_4 = canvas.create_image(
            672.0,
            198.0,
            image=entry_image_4
        )
        entry_4 = Entry(
            bd=0,
            bg="#D9D9D9",
            fg="#000716",
            highlightthickness=0
        )
        entry_4.place(
            x=580.0,
            y=180.0,
            width=184.0,
            height=34.0
        )

        entry_image_5 = PhotoImage(
            file=relative_to_assets("entry_5.png"))
        entry_bg_5 = canvas.create_image(
            672.0,
            252.0,
            image=entry_image_5
        )
        entry_5 = Entry(
            bd=0,
            bg="#D9D9D9",
            fg="#000716",
            highlightthickness=0
        )
        entry_5.place(
            x=580.0,
            y=234.0,
            width=184.0,
            height=34.0
        )

        entry_image_6 = PhotoImage(
            file=relative_to_assets("entry_6.png"))
        entry_bg_6 = canvas.create_image(
            672.0,
            306.0,
            image=entry_image_6
        )
        entry_6 = Entry(
            bd=0,
            bg="#D9D9D9",
            fg="#000716",
            highlightthickness=0
        )
        entry_6.place(
            x=580.0,
            y=288.0,
            width=184.0,
            height=34.0
        )

        entry_image_7 = PhotoImage(
            file=relative_to_assets("entry_7.png"))
        entry_bg_7 = canvas.create_image(
            225.0,
            132.5,
            image=entry_image_7
        )
        entry_7 = Entry(
            bd=0,
            bg="#D9D9D9",
            fg="#000716",
            highlightthickness=0
        )
        entry_7.place(
            x=133.0,
            y=119.0,
            width=184.0,
            height=25.0
        )

        canvas.create_text(
            55.0,
            45.0,
            anchor="nw",
            text="Usuario:",
            fill="#000000",
            font=("Inter", 20 * -1)
        )

        canvas.create_text(
            509.0,
            132.0,
            anchor="nw",
            text="Correo:",
            fill="#000000",
            font=("Inter", 20 * -1)
        )

        canvas.create_text(
            484.0,
            294.0,
            anchor="nw",
            text="Dirección:",
            fill="#000000",
            font=("Inter", 20 * -1)
        )

        canvas.create_text(
            414.0,
            346.0,
            anchor="nw",
            text="Es administrador:",
            fill="#000000",
            font=("Inter", 20 * -1)
        )

        canvas.create_text(
            394.0,
            77.0,
            anchor="nw",
            text="Nombre de usuario:",
            fill="#000000",
            font=("Inter", 20 * -1)
        )

        canvas.create_text(
            394.0,
            242.0,
            anchor="nw",
            text="Repetir contraseña:",
            fill="#000000",
            font=("Inter", 20 * -1)
        )

        canvas.create_text(
            465.0,
            187.0,
            anchor="nw",
            text="Contraseña:",
            fill="#000000",
            font=("Inter", 20 * -1)
        )

        canvas.create_text(
            509.0,
            30.0,
            anchor="nw",
            text="Nuevo registro",
            fill="#000000",
            font=("Inter", 20 * -1)
        )

        canvas.create_text(
            18.0,
            122.0,
            anchor="nw",
            text="Contraseña:",
            fill="#000000",
            font=("Inter", 20 * -1)
        )
        window.resizable(False, False)
        window.mainloop()
